name: Siri Shortcut

on: repository_dispatch  

jobs:
  label-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install
        working-directory: ./.github/issues-autolabeler
      - name: luis_label
        uses: ./.github/issues-autolabeler
        with:
          issue: ${{github.event.client_payload.description}}
        env:
          LUIS_APP_ID: ${{ secrets.LUIS_APP_ID }}
          LUIS_APP_KEY: ${{ secrets.LUIS_APP_KEY }}
      - name: create_issue
        uses: actions/github-script@v3
        env:
          owner: ${{ github.actor }}
          body: ${{ github.event.client_payload.description }}
          repository: ${{ github.repository }}
        with:
          github-token: ${{secrets.PAT_TOKEN}}
          script: |
            const { body, owner, repository } = process.env;
            const label = process.env.ISSUE_LABEL;
            let title =`New ${label} issue by Siri`;
            github.issues.create({
              ...context.repo,
              title,
              body,
              labels: [process.env.ISSUE_LABEL]
            });
